apiVersion: v1
kind: Service
metadata:
  name: rain
  labels:
    app: rain
spec:
  ports:
    - port: 8085
      name: http
  selector:
    app: rain
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rain-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rain
        version: v1
    spec:
      nodeSelector:
        internet: "true"
      containers:
        - name: rain
          image: registry.njuics.cn/wdongyu/drone-test:VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
---